name: SourceForge upload

on:
  workflow_dispatch:
    inputs:
        NIKGAPPS_VER:
          description: 'NikGApps release date/version to download'
          required: true
        SYSTEMLESSGAPPS_URL:
          description: 'Systemless GApps repo to clone (edit if fork)'
          required: true
          default: 'https://github.com/chickendrop89/systemless-gapps'
        NIKGAPPS_ANDROID_REL_1:
          description: 'NikGApps android release version (1)'
          required: true
        NIKGAPPS_ANDROID_REL_2:
          description: 'NikGApps android release version (2)'
          required: true

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: SSH Known Hosts
      uses: truemark/ssh-known-hosts-action@v1
      with:
        scan-hosts: web.sourceforge.net

    - name: Set build date variable
      run: |
        echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      id: date

    - name: Clone Systemless GApps Repository
      run: |
        git clone --recurse-submodules ${{ github.event.inputs.SYSTEMLESSGAPPS_URL }} systemless-gapps
        echo "workspace-folder=$(pwd)/systemless-gapps" >> $GITHUB_OUTPUT
      id: pwd

    - name: "Install Python and requirements"
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - run: pip install -r requirements.txt

    - name: Download NikGApps Packages
      run: |
        sf_url=https://sourceforge.net/projects/nikgapps/files/Releases
        sf_script=$(pwd)/.github/sourceforge-folder-downloader/sf-downloader.sh

        $sf_script $sf_url/${{ github.event.inputs.NIKGAPPS_ANDROID_REL_1 }}/${{ github.event.inputs.NIKGAPPS_VER }} ${{ github.event.inputs.NIKGAPPS_ANDROID_REL_1 }};
        $sf_script $sf_url/${{ github.event.inputs.NIKGAPPS_ANDROID_REL_2 }}/${{ github.event.inputs.NIKGAPPS_VER }} ${{ github.event.inputs.NIKGAPPS_ANDROID_REL_2 }};
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Build Systemless GApps Modules
      run: |
        directories=("${{ github.event.inputs.NIKGAPPS_ANDROID_REL_1 }}" "${{ github.event.inputs.NIKGAPPS_ANDROID_REL_2 }}")

        for dir in $directories;
          do
            for zipfile in $dir/*.zip; 
              do
                if [[ ! -f "$zipfile" ]]; 
                  then
                    continue
                fi

                python main.py $zipfile $dir
            done
        done
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Publish Modules to SourceForge
      run: |
        directories=("${{ github.event.inputs.NIKGAPPS_ANDROID_REL_1 }}" "${{ github.event.inputs.NIKGAPPS_ANDROID_REL_2 }}")

        for dir in $directories; 
          do
            for zipfile in $dir/*.zip;
              do
                if [[ ! -f "$zipfile" ]]; 
                  then
                    continue
                fi
                
                sshpass -p ${{ secrets.SOURCEFORGE_PASSWORD }} rsync $zipfile ${{ secrets.SOURCEFORGE_USERNAME }}@web.sourceforge.net:/home/frs/project/systemless-gapps/$dir/${{ github.event.inputs.NIKGAPPS_VER }}/
            done
        done
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Create a GitHub relese
      uses: softprops/action-gh-release@v1
      with:
        name: Systemless GApps ${{ github.event.inputs.NIKGAPPS_VER }}
        tag_name: ${{ steps.date.outputs.builddate }}
        body: |
          NikGApps version: ${{ github.event.inputs.NIKGAPPS_VER }}
          Build date: ${{ steps.date.outputs.builddate }}

          [![Download Systemless GApps](https://a.fsdn.com/con/app/sf-download-button)](https://sourceforge.net/projects/systemless-gapps/files)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
